### PR TITLE
Update to Qt 6.4.2

### PR DESCRIPTION
**Pull request by ntadej**
Update to Qt 6.4.2.

Also add missing changelog item from a fix earlier.

### CODE REVIEW

**Comment by ntadej** [comment]
Hi @louwers, do you mind if I tag you also on MRs of this repository? These are Qt QML bindings for MapLibre Native. Would be good to get reviews also here 😊

**Comment by louwers** [comment]
@ntadej that is not a problem! I have yet to set up a local dev environment for Qt, my focus has been on Android and iOS so far. So it might take a few days until I can approve it myself, but @birkskyum also seems active approving PRs.

**Comment by ntadej** [comment]
> Edit: still need the right permissions for this repo as well. (Could you have a look @wipfli?)

I added you as Maintainer (as I'm admin of this repo). I guess I could also make you admin (but Oliver can confirm).

**Comment by ntadej** [comment]
Oh, and no problem if you need time to setup the environment. Note that here proper tests are still missing, but there is a minimal example.

**Comment by wipfli** [comment]
Thanks for asking @ntadej. I would say that time tracking should be restricted to core repositories as defined in https://github.com/maplibre/maplibre/blob/main/PROJECT_TIERS.md and that our focus is on iOS and Android in the paid maintainer native role. Of course, @louwers you are free to help out on other platforms as a volunteer, but in this initial phase let us focus the tracked time on iOS and Android...

**Review by birkskyum — APPROVED** [review]

**Pull request merged**
