### PR TITLE
Update release workflow

### PR DESCRIPTION
**Pull request by ntadej**
Update release workflow to make sure symlinks are preserved.

### CODE REVIEW

**Comment by wipfli** [comment]
I guess when initially setting up this repository it was useful to move fast and merge without approval from a second person. Do you think that things are stable enough now that we could transition to the regime we have usually in the MapLibre repo which is to only merge pull requests after someone else approved them, no matter how small the change?

**Comment by ntadej** [comment]
I say yes, although typos also slipped in native in spite of reviews 😉. Maybe we should get more careful.

**Comment by wipfli** [comment]
Absolutely! Cool, thanks. Is branch protection turned on for the main branch here? I guess yes since this is one of the onbording points, right?

**Comment by wipfli** [comment]
And feel free to ping me or someone in the native slack channel if you don't get a review...

**Comment by ntadej** [comment]
Yes, it is. I did everything through MRs for a while.

**Pull request merged**
